Add more logging for update task
This commit adds more explicit logging for when the update task runs to
delete dangling users off of each static VM.

KONFLUX-10713

Assisted-by: Gemini

diff --git a/deploy/operator/update-host.yaml b/deploy/operator/update-host.yaml
--- a/deploy/operator/update-host.yaml
+++ b/deploy/operator/update-host.yaml
@@ -27,17 +27,29 @@ spec:
         export SSH_HOST=$(params.USER)@$(params.HOST)
         ssh -i /tmp/master_key -o StrictHostKeyChecking=no $SSH_HOST "sudo dnf update -y"
 
-        #now clean up any dangling users, if their cleanup failed for whatever reason
-
+        # Clean up any dangling users, if their cleanup failed for whatever reason
         cat >script.sh <<EOF
         threshold=$(date -d "1 day ago" +%s)
         cd /home
-        for file in u-*; do
-          # Check if the file is a regular file and older than the threshold
-          if [[ $(stat -c "%Y" "$file") -lt $threshold ]]; then
-          # Delete the user
-          sudo userdel -f -r -Z $file
-          echo "Deleted: $file"
+        for user_dir in u-*; do
+          # Skip non-directory entries
+          if [[ ! -d "$user_dir" ]]; then
+            continue
+          fi
+
+          # Obfuscate user directory for logging
+          obfuscated_dir="${user_dir:0:2}**********${user_dir: -3:3}"
+
+          # Delete the user & directory if the last modification time is older than the threshold
+          if [[ $(stat -c "%Y" "$user_dir") -lt $threshold ]]; then
+            echo "Deleting old user & its /home directory: $obfuscated_dir..."
+            sudo userdel -f -r -Z $user_dir
+            # Confirm deletion of user and user directory (0) or just user directory (6)
+            if [ $? -eq 0 ] || [ $? -eq 6]; then
+                echo "User $obfuscated_name was successfully deleted"
+            else
+                echo "User $obfuscated_name deletion failed (exit code $?)."
+            fi
           fi
         done
         EOF
