Escape local variables in MPC tasks
This is so that the variables written to `script.sh` are expanded at
runtime.

KONFLUX-10713

diff --git a/deploy/operator/update-host.yaml b/deploy/operator/update-host.yaml
--- a/deploy/operator/update-host.yaml
+++ b/deploy/operator/update-host.yaml
@@ -43,11 +43,11 @@ spec:
         SSH_OPTS="-i /tmp/master_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
 
         SSH_UPDATE_OUTPUT=$(
-            ssh $SSH_OPTS $SSH_HOST "sudo dnf update -y" 2>&1
+            ssh "$SSH_OPTS" "$SSH_HOST" "sudo dnf update -y" 2>&1
         ) || {
             # If the command fails, the `||` block executes.
             # Note: Using `||` suppresses set -e for this line.
-            echo "{message: "Remote Update Output: $SSH_UPDATE_OUTPUT", level: "WARNING"}" >&2
+            echo "{message: "Remote Update Output: "$SSH_UPDATE_OUTPUT"", level: "WARNING"}" >&2
             exit 1
         }
         echo "{message: "SSH to $(params.HOST) was successful.", level: "INFO"}"
@@ -57,7 +57,7 @@ spec:
         threshold=\$(date -d "1 day ago" +%s)
         cd /home
         for user_dir in u-*; do
-          echo "{message: "Checking '$user_dir' against threshold...", level: "INFO"}"
+          echo "{message: "Checking '\$user_dir' against threshold...", level: "INFO"}"
 
           # Skip non-directory entries
           if [[ ! -d "\$user_dir" ]]; then
@@ -65,23 +65,23 @@ spec:
           fi
 
           # Delete the user & directory if the last modification time is older than the threshold
-          if [[ $(stat -c "%Y" "$user_dir") -lt $threshold ]]; then
+          if [[ \$(stat -c "%Y" "\$user_dir") -lt "\$threshold" ]]; then
 
             # try to kill all processes associated with $user_dir
-            sudo killall -9 -u "$user_dir"
+            sudo killall -9 -u "\$user_dir"
             KILL_STATUS=$?
             if [ $KILL_STATUS -ne 0 ]; then
-              echo "{message: "Could not kill all processes associated with user `$user_dir` (exit code $KILL_STATUS).", level: "WARNING"}"
+              echo "{message: "Could not kill all processes associated with user `\$user_dir` (exit code \$KILL_STATUS).", level: "WARNING"}"
             fi
 
-            echo "{message: "Deleting old home directory '$user_dir' & its associated user...", level: "INFO"}"
-            sudo userdel -f -r -Z "$user_dir"
+            echo "{message: "Deleting old home directory '\$user_dir' & its associated user...", level: "INFO"}"
+            sudo userdel -f -r -Z "\$user_dir"
             # Confirm deletion of user and user directory (0) or just user directory (6)
             DELETE_STATUS=$? # Capture status immediately
             if [ $DELETE_STATUS -eq 0 ] || [ $DELETE_STATUS -eq 6 ]; then
-                echo "{message: "User $user_dir was successfully deleted.", level: "INFO"}"
+                echo "{message: "User \$user_dir was successfully deleted.", level: "INFO"}"
             else
-                echo "{message: User $user_dir deletion failed (exit code $DELETE_STATUS).", level: "WARNING"}"
+                echo "{message: User \$user_dir deletion failed (exit code \$DELETE_STATUS).", level: "WARNING"}"
             fi
           fi
         done
@@ -89,7 +89,7 @@ spec:
 
         # Execute script to prune dangling users remotely
         SSH_USER_DEL_OUTPUT=$(
-            ssh $SSH_OPTS $SSH_HOST "bash -s" <script.sh 2>&1
+            ssh "$SSH_OPTS" "$SSH_HOST" "bash -s" <script.sh 2>&1
         ) || {
             # If the command fails, the `||` block executes.
             # Note: Using `||` suppresses set -e for this line.
